// aipolicy -- templates, presets, tabs, zip, URL params, theme, clipboard

'use strict';

// ============================================
// Preset Definitions
// ============================================

const PRESETS = {
  permissive: {
    ai_usage: 'permitted',
    ai_code: 'accepted',
    ai_cicd: 'permitted',
    training_optout: 'no',
    code_style: '',
    test_reqs: 'none',
    restricted_paths: '',
    review_reqs: 'none',
    claude_handling: 'separate',
  },
  standard: {
    ai_usage: 'permitted-with-review',
    ai_code: 'requires-review',
    ai_cicd: 'permitted',
    training_optout: 'yes',
    code_style: '',
    test_reqs: 'recommended',
    restricted_paths: '',
    review_reqs: 'significant-changes',
    claude_handling: 'separate',
  },
  strict: {
    ai_usage: 'restricted',
    ai_code: 'not-accepted',
    ai_cicd: 'restricted',
    training_optout: 'yes',
    code_style: '',
    test_reqs: 'required-before-merge',
    restricted_paths: '',
    review_reqs: 'all-ai-prs',
    claude_handling: 'separate',
  },
};

// Human-readable labels for option values
const LABELS = {
  ai_usage: {
    'permitted': 'Permitted',
    'permitted-with-review': 'Permitted with review',
    'restricted': 'Restricted',
    'prohibited': 'Prohibited',
  },
  ai_code: {
    'accepted': 'Accepted',
    'requires-review': 'Requires review',
    'requires-attribution': 'Requires attribution',
    'not-accepted': 'Not accepted',
  },
  ai_cicd: {
    'permitted': 'Permitted',
    'restricted': 'Restricted',
    'prohibited': 'Prohibited',
  },
  training_optout: {
    'yes': 'Yes',
    'no': 'No',
  },
  test_reqs: {
    'none': 'None',
    'recommended': 'Recommended',
    'required-before-merge': 'Required before merge',
  },
  review_reqs: {
    'none': 'None',
    'significant-changes': 'Significant changes',
    'all-ai-prs': 'All AI-generated PRs',
  },
};

const FOOTER = '\n---\n*Generated by [aipolicy.1mb.dev](https://aipolicy.1mb.dev) · v1.0*\n';

// ============================================
// Template Functions
// ============================================

function escapeMarkdown(str) {
  if (!str) return '';
  return str.replace(/[<>&"']/g, (c) => {
    const map = { '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&#39;' };
    return map[c];
  });
}

function generateAiPolicy(opts) {
  const usage = LABELS.ai_usage[opts.ai_usage] || opts.ai_usage;
  const code = LABELS.ai_code[opts.ai_code] || opts.ai_code;
  const cicd = LABELS.ai_cicd[opts.ai_cicd] || opts.ai_cicd;
  const optout = opts.training_optout === 'yes';

  let md = `# AI Policy

This document declares how AI tools are used in this project.

## AI Tool Usage

**Policy:** ${usage}

`;

  if (opts.ai_usage === 'permitted') {
    md += `AI-powered development tools may be used without restriction. Contributors are free to use AI assistants for code generation, review, and documentation.\n\n`;
  } else if (opts.ai_usage === 'permitted-with-review') {
    md += `AI-powered development tools may be used, but AI-assisted contributions must go through the standard review process. Reviewers should be aware when a contribution involved AI assistance.\n\n`;
  } else if (opts.ai_usage === 'restricted') {
    md += `AI tool usage is restricted. Contributors must obtain approval before using AI tools for contributions to this project. Approved use cases and tools will be documented below.\n\n`;
  } else {
    md += `AI-powered development tools are not permitted for contributions to this project. All contributions must be human-authored.\n\n`;
  }

  md += `## AI-Generated Code

**Policy:** ${code}

`;

  if (opts.ai_code === 'accepted') {
    md += `AI-generated code is accepted in this project. No special attribution or review process is required beyond the standard contribution workflow.\n\n`;
  } else if (opts.ai_code === 'requires-review') {
    md += `AI-generated code is accepted but must be reviewed by a human maintainer before merging. Contributors should indicate when a pull request contains AI-generated code.\n\n`;
  } else if (opts.ai_code === 'requires-attribution') {
    md += `AI-generated code is accepted but must be clearly attributed. Pull requests containing AI-generated code should note which portions were AI-generated and which tool was used.\n\n`;
  } else {
    md += `AI-generated code is not accepted in this project. All code contributions must be human-authored. Pull requests identified as containing AI-generated code will not be merged.\n\n`;
  }

  md += `## AI in CI/CD

**Policy:** ${cicd}

`;

  if (opts.ai_cicd === 'permitted') {
    md += `AI tools may be used in CI/CD pipelines, including automated code analysis, test generation, and deployment assistance.\n\n`;
  } else if (opts.ai_cicd === 'restricted') {
    md += `AI tools in CI/CD pipelines require explicit approval. Any AI-powered automation must be reviewed and approved by a maintainer before integration into the pipeline.\n\n`;
  } else {
    md += `AI tools are not permitted in CI/CD pipelines. All automated processes must use deterministic, non-AI tooling.\n\n`;
  }

  md += `## Training Data

**Opt-out:** ${optout ? 'Yes' : 'No'}

`;

  if (optout) {
    md += `This project requests that its code not be used for AI model training. This preference should be respected by AI tool providers and data collection services.\n`;
  } else {
    md += `This project does not opt out of AI training data collection. Standard platform terms apply.\n`;
  }

  md += FOOTER;
  return md;
}

function generateAgents(opts) {
  const testLabel = LABELS.test_reqs[opts.test_reqs] || opts.test_reqs;
  const reviewLabel = LABELS.review_reqs[opts.review_reqs] || opts.review_reqs;
  const codeStyle = escapeMarkdown(opts.code_style);
  const restrictedPaths = escapeMarkdown(opts.restricted_paths);

  let md = `# Agents

Rules and guidelines for AI coding agents working in this repository.

## General

- Follow existing code conventions and patterns
- Do not modify files outside the scope of the assigned task
- Ask for clarification rather than making assumptions about ambiguous requirements
`;

  if (codeStyle) {
    md += `\n## Code Style\n\n${codeStyle}\n`;
  }

  md += `\n## Testing\n\n**Requirement:** ${testLabel}\n\n`;

  if (opts.test_reqs === 'none') {
    md += `No specific testing requirements for AI-generated changes. Follow the project's existing testing conventions if any.\n`;
  } else if (opts.test_reqs === 'recommended') {
    md += `Tests are recommended for AI-generated changes. Include tests for new functionality and verify that existing tests pass before submitting.\n`;
  } else {
    md += `Tests are required for all AI-generated changes. Pull requests without adequate test coverage will not be merged. Run the full test suite before submitting.\n`;
  }

  if (restrictedPaths) {
    const paths = restrictedPaths.split(',').map(p => p.trim()).filter(Boolean);
    md += `\n## Restricted Paths\n\nDo not modify the following files or directories:\n\n`;
    for (const p of paths) {
      md += `- \`${p}\`\n`;
    }
  }

  md += `\n## Review\n\n**Requirement:** ${reviewLabel}\n\n`;

  if (opts.review_reqs === 'none') {
    md += `No special review requirements for AI-generated pull requests beyond the standard process.\n`;
  } else if (opts.review_reqs === 'significant-changes') {
    md += `Pull requests with significant AI-generated changes require human review. Minor fixes and documentation updates may follow the standard process.\n`;
  } else {
    md += `All AI-generated pull requests require human review before merging, regardless of scope or size.\n`;
  }

  md += FOOTER;
  return md;
}

function generateClaude(opts) {
  if (opts.claude_handling === 'symlink') {
    return `# CLAUDE.md

This file can be replaced with a symlink to AGENTS.md:

\`\`\`
ln -sf AGENTS.md CLAUDE.md
\`\`\`

The rules in AGENTS.md apply to Claude Code. No additional Claude-specific configuration is needed.
${FOOTER}`;
  }

  let md = `# CLAUDE.md

Configuration for Claude Code in this repository. See AGENTS.md for general agent rules.

## Applies

All rules from AGENTS.md apply to Claude Code sessions in this repository.

`;

  if (opts.test_reqs === 'required-before-merge') {
    md += `## Testing

Run the full test suite before proposing changes. Do not submit pull requests with failing tests.

`;
  }

  if (opts.restricted_paths) {
    md += `## Restricted

Do not read or modify files listed in the Restricted Paths section of AGENTS.md.

`;
  }

  md += `## Behavior

- Prefer editing existing files over creating new ones
- Keep changes minimal and focused on the task
- Do not add dependencies without explicit approval
`;

  md += FOOTER;
  return md;
}

// ============================================
// State
// ============================================

const state = {
  preset: 'standard',
  options: { ...PRESETS.standard },
  activeTab: 'policy',
  modified: false,
};

function getGeneratedFiles() {
  return {
    policy: generateAiPolicy(state.options),
    agents: generateAgents(state.options),
    claude: generateClaude(state.options),
  };
}

// ============================================
// Render
// ============================================

function renderPreview() {
  const files = getGeneratedFiles();
  const panels = {
    policy: document.getElementById('panel-policy'),
    agents: document.getElementById('panel-agents'),
    claude: document.getElementById('panel-claude'),
  };

  for (const [key, el] of Object.entries(panels)) {
    if (el) el.textContent = files[key];
  }
}

function renderPresetCards() {
  const cards = document.querySelectorAll('.preset-card');
  for (const card of cards) {
    const isSelected = card.dataset.preset === state.preset;
    card.setAttribute('aria-checked', isSelected ? 'true' : 'false');

    const label = card.querySelector('.preset-label');
    if (label) {
      const baseName = card.dataset.preset.charAt(0).toUpperCase() + card.dataset.preset.slice(1);
      label.textContent = (isSelected && state.modified) ? `${baseName} (modified)` : baseName;
    }
  }
}

function renderTabs() {
  const tabMap = { policy: 'tab-policy', agents: 'tab-agents', claude: 'tab-claude' };
  const panelMap = { policy: 'panel-policy', agents: 'panel-agents', claude: 'panel-claude' };

  for (const [key, tabId] of Object.entries(tabMap)) {
    const tab = document.getElementById(tabId);
    const panel = document.getElementById(panelMap[key]);
    if (!tab || !panel) continue;

    const isActive = key === state.activeTab;
    tab.setAttribute('aria-selected', isActive ? 'true' : 'false');
    tab.setAttribute('tabindex', isActive ? '0' : '-1');
    panel.hidden = !isActive;
  }
}

function renderOptions() {
  for (const [key, value] of Object.entries(state.options)) {
    const el = document.querySelector(`[data-param="${key}"]`);
    if (el) el.value = value;
  }
}

function checkModified() {
  const base = PRESETS[state.preset];
  state.modified = Object.keys(base).some(k => state.options[k] !== base[k]);
}

function updateUrl() {
  const params = new URLSearchParams();
  params.set('preset', state.preset);

  const base = PRESETS[state.preset];
  for (const [key, value] of Object.entries(state.options)) {
    if (value !== base[key] && value !== '') {
      params.set(key, value);
    }
  }

  const qs = params.toString();
  const url = qs ? `${location.pathname}?${qs}` : location.pathname;
  history.replaceState(null, '', url);
}

function render() {
  renderPreview();
  renderPresetCards();
  renderTabs();
  updateUrl();
}

// ============================================
// Preset Switching
// ============================================

function initPresets() {
  const cards = document.querySelectorAll('.preset-card');
  for (const card of cards) {
    card.addEventListener('click', () => {
      const preset = card.dataset.preset;
      if (!PRESETS[preset]) return;
      state.preset = preset;
      state.options = { ...PRESETS[preset] };
      state.modified = false;
      renderOptions();
      render();
    });
  }
}

// ============================================
// Tab Navigation
// ============================================

function initTabs() {
  const tabs = document.querySelectorAll('[role="tab"]');
  const tabKeys = ['policy', 'agents', 'claude'];

  for (const tab of tabs) {
    tab.addEventListener('click', () => {
      const key = tab.id.replace('tab-', '');
      state.activeTab = key;
      renderTabs();
    });

    tab.addEventListener('keydown', (e) => {
      const currentIdx = tabKeys.indexOf(state.activeTab);
      let newIdx = -1;

      if (e.key === 'ArrowRight') newIdx = (currentIdx + 1) % tabKeys.length;
      else if (e.key === 'ArrowLeft') newIdx = (currentIdx - 1 + tabKeys.length) % tabKeys.length;
      else if (e.key === 'Home') newIdx = 0;
      else if (e.key === 'End') newIdx = tabKeys.length - 1;

      if (newIdx >= 0) {
        e.preventDefault();
        state.activeTab = tabKeys[newIdx];
        renderTabs();
        document.getElementById(`tab-${tabKeys[newIdx]}`).focus();
      }
    });
  }
}

// ============================================
// Customize Panel
// ============================================

function initCustomize() {
  const toggle = document.querySelector('.customize-toggle');
  const panel = document.getElementById('customize-panel');
  if (!toggle || !panel) return;

  toggle.addEventListener('click', () => {
    const expanded = toggle.getAttribute('aria-expanded') === 'true';
    toggle.setAttribute('aria-expanded', expanded ? 'false' : 'true');
    panel.classList.toggle('open', !expanded);
  });

  // Listen for changes on all option inputs
  panel.addEventListener('change', (e) => {
    const param = e.target.dataset.param;
    if (!param) return;
    state.options[param] = e.target.value;
    checkModified();
    render();
  });

  panel.addEventListener('input', (e) => {
    if (e.target.type !== 'text') return;
    const param = e.target.dataset.param;
    if (!param) return;
    state.options[param] = e.target.value;
    checkModified();
    render();
  });
}

// ============================================
// URL-as-Config (load from URL)
// ============================================

function loadFromUrl() {
  const params = new URLSearchParams(location.search);
  if (!params.has('preset')) return;

  const preset = params.get('preset');
  if (!PRESETS[preset]) return;

  state.preset = preset;
  state.options = { ...PRESETS[preset] };

  // Apply overrides
  const validParams = Object.keys(PRESETS.standard);
  for (const key of validParams) {
    if (params.has(key)) {
      const val = params.get(key);
      // Validate enum values
      if (LABELS[key]) {
        if (LABELS[key][val]) state.options[key] = val;
      } else {
        // Freeform text params
        state.options[key] = val;
      }
    }
  }

  checkModified();
  renderOptions();
}

// ============================================
// Copy to Clipboard
// ============================================

function initCopy() {
  const btn = document.querySelector('.copy-btn');
  const status = document.getElementById('copy-status');
  if (!btn) return;

  btn.addEventListener('click', async () => {
    const files = getGeneratedFiles();
    const content = files[state.activeTab];

    try {
      await navigator.clipboard.writeText(content);
      btn.textContent = 'Copied';
      btn.classList.add('copied');
      if (status) status.textContent = 'File content copied to clipboard';
      setTimeout(() => {
        btn.textContent = 'Copy';
        btn.classList.remove('copied');
        if (status) status.textContent = '';
      }, 1500);
    } catch (e) {
      // Fallback: select text in the active panel
      const panel = document.getElementById(`panel-${state.activeTab}`);
      if (panel) {
        const range = document.createRange();
        range.selectNodeContents(panel);
        const sel = window.getSelection();
        sel.removeAllRanges();
        sel.addRange(range);
        btn.textContent = 'Select all + copy manually';
        setTimeout(() => { btn.textContent = 'Copy'; }, 3000);
      }
    }
  });
}

// ============================================
// ZIP Download
// ============================================

function createZip(files) {
  // Manual ZIP construction: stored (no compression) entries
  // Structure: [local file header + data] * N + central directory + EOCD

  const encoder = new TextEncoder();
  const entries = files.map(f => ({
    name: encoder.encode(f.name),
    data: encoder.encode(f.content),
  }));

  // CRC-32 lookup table
  const crcTable = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let j = 0; j < 8; j++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
    crcTable[i] = c;
  }
  function crc32(data) {
    let crc = 0xFFFFFFFF;
    for (let i = 0; i < data.length; i++) crc = crcTable[(crc ^ data[i]) & 0xFF] ^ (crc >>> 8);
    return (crc ^ 0xFFFFFFFF) >>> 0;
  }

  // Calculate total size
  let localSize = 0;
  for (const e of entries) localSize += 30 + e.name.length + e.data.length;
  let cdSize = 0;
  for (const e of entries) cdSize += 46 + e.name.length;
  const eocdSize = 22;
  const totalSize = localSize + cdSize + eocdSize;

  const buf = new ArrayBuffer(totalSize);
  const view = new DataView(buf);
  let offset = 0;
  const offsets = [];

  // Local file headers + data
  for (const e of entries) {
    const crc = crc32(e.data);
    offsets.push({ offset, crc, size: e.data.length, nameLen: e.name.length });

    view.setUint32(offset, 0x04034B50, true); // signature
    view.setUint16(offset + 4, 20, true);      // version needed
    view.setUint16(offset + 6, 0, true);       // flags
    view.setUint16(offset + 8, 0, true);       // compression (stored)
    view.setUint16(offset + 10, 0, true);      // mod time
    view.setUint16(offset + 12, 0, true);      // mod date
    view.setUint32(offset + 14, crc, true);    // crc-32
    view.setUint32(offset + 18, e.data.length, true); // compressed size
    view.setUint32(offset + 22, e.data.length, true); // uncompressed size
    view.setUint16(offset + 26, e.name.length, true); // filename length
    view.setUint16(offset + 28, 0, true);      // extra field length
    offset += 30;

    new Uint8Array(buf, offset, e.name.length).set(e.name);
    offset += e.name.length;

    new Uint8Array(buf, offset, e.data.length).set(e.data);
    offset += e.data.length;
  }

  // Central directory
  const cdOffset = offset;
  for (let i = 0; i < entries.length; i++) {
    const e = entries[i];
    const o = offsets[i];

    view.setUint32(offset, 0x02014B50, true); // signature
    view.setUint16(offset + 4, 20, true);      // version made by
    view.setUint16(offset + 6, 20, true);      // version needed
    view.setUint16(offset + 8, 0, true);       // flags
    view.setUint16(offset + 10, 0, true);      // compression
    view.setUint16(offset + 12, 0, true);      // mod time
    view.setUint16(offset + 14, 0, true);      // mod date
    view.setUint32(offset + 16, o.crc, true);  // crc-32
    view.setUint32(offset + 20, o.size, true); // compressed size
    view.setUint32(offset + 24, o.size, true); // uncompressed size
    view.setUint16(offset + 28, o.nameLen, true); // filename length
    view.setUint16(offset + 30, 0, true);      // extra field length
    view.setUint16(offset + 32, 0, true);      // comment length
    view.setUint16(offset + 34, 0, true);      // disk number start
    view.setUint16(offset + 36, 0, true);      // internal file attributes
    view.setUint32(offset + 38, 0, true);      // external file attributes
    view.setUint32(offset + 42, o.offset, true); // local header offset
    offset += 46;

    new Uint8Array(buf, offset, e.name.length).set(e.name);
    offset += e.name.length;
  }

  // End of central directory record
  view.setUint32(offset, 0x06054B50, true);    // signature
  view.setUint16(offset + 4, 0, true);         // disk number
  view.setUint16(offset + 6, 0, true);         // cd disk number
  view.setUint16(offset + 8, entries.length, true);  // cd entries on disk
  view.setUint16(offset + 10, entries.length, true); // cd entries total
  view.setUint32(offset + 12, offset - cdOffset, true); // cd size
  view.setUint32(offset + 16, cdOffset, true); // cd offset
  view.setUint16(offset + 20, 0, true);        // comment length

  return new Blob([buf], { type: 'application/zip' });
}

function initDownload() {
  const btn = document.querySelector('.download-btn');
  const confirm = document.querySelector('.download-confirm');
  if (!btn) return;

  btn.addEventListener('click', () => {
    const files = getGeneratedFiles();
    const zipFiles = [
      { name: 'AI_POLICY.md', content: files.policy },
      { name: 'AGENTS.md', content: files.agents },
      { name: 'CLAUDE.md', content: files.claude },
    ];

    try {
      const blob = createZip(zipFiles);
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      const presetName = state.modified ? 'custom' : state.preset;
      a.href = url;
      a.download = `aipolicy-${presetName}.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      if (confirm) {
        confirm.textContent = '3 files downloaded';
        confirm.classList.add('visible');
        setTimeout(() => {
          confirm.classList.remove('visible');
          confirm.textContent = '';
        }, 2000);
      }
    } catch (e) {
      // Blob API unavailable -- fall back to copy buttons
      btn.style.display = 'none';
    }
  });
}

// ============================================
// Init Preview
// ============================================

function initPreview() {
  loadFromUrl();
  renderOptions();
  render();
}

// ============================================
// Theme Toggle
// ============================================

function initTheme() {
  const toggle = document.querySelector('.theme-toggle');
  if (!toggle) return;

  let stored = 'auto';
  try {
    const val = localStorage.getItem('aipolicy-theme');
    if (val === 'light' || val === 'dark' || val === 'auto') stored = val;
  } catch (e) {
    // localStorage unavailable (private browsing) -- default to auto
  }

  applyTheme(stored);
  updateToggleState(toggle, stored);

  toggle.addEventListener('click', (e) => {
    const btn = e.target.closest('button[data-theme-value]');
    if (!btn) return;
    const value = btn.dataset.themeValue;
    applyTheme(value);
    updateToggleState(toggle, value);
    try {
      if (value === 'auto') {
        localStorage.removeItem('aipolicy-theme');
      } else {
        localStorage.setItem('aipolicy-theme', value);
      }
    } catch (e) {
      // localStorage unavailable -- theme still applied for this session
    }
  });
}

function applyTheme(value) {
  if (value === 'auto') {
    document.documentElement.removeAttribute('data-theme');
  } else {
    document.documentElement.setAttribute('data-theme', value);
  }
}

function updateToggleState(toggle, active) {
  for (const btn of toggle.querySelectorAll('button')) {
    btn.setAttribute('aria-pressed', btn.dataset.themeValue === active ? 'true' : 'false');
  }
}

// ============================================
// Init
// ============================================

document.addEventListener('DOMContentLoaded', () => {
  initTheme();
  initPresets();
  initTabs();
  initCustomize();
  initCopy();
  initDownload();
  initPreview();
});
