// aipolicy -- templates, presets, tabs, zip, URL params, theme, clipboard

'use strict';

// ============================================
// Preset Definitions
// ============================================

const PRESETS = {
  permissive: {
    ai_usage: 'permitted',
    ai_code: 'accepted',
    ai_cicd: 'permitted',
    training_optout: 'no',
    code_style: '',
    test_reqs: 'none',
    restricted_paths: '',
    review_reqs: 'none',
    claude_handling: 'separate',
  },
  standard: {
    ai_usage: 'permitted-with-review',
    ai_code: 'requires-review',
    ai_cicd: 'permitted',
    training_optout: 'yes',
    code_style: '',
    test_reqs: 'recommended',
    restricted_paths: '',
    review_reqs: 'significant-changes',
    claude_handling: 'separate',
  },
  strict: {
    ai_usage: 'restricted',
    ai_code: 'not-accepted',
    ai_cicd: 'restricted',
    training_optout: 'yes',
    code_style: '',
    test_reqs: 'required-before-merge',
    restricted_paths: '',
    review_reqs: 'all-ai-prs',
    claude_handling: 'separate',
  },
};

// Human-readable labels for option values
const LABELS = {
  ai_usage: {
    'permitted': 'Permitted',
    'permitted-with-review': 'Permitted with review',
    'restricted': 'Restricted',
    'prohibited': 'Prohibited',
  },
  ai_code: {
    'accepted': 'Accepted',
    'requires-review': 'Requires review',
    'requires-attribution': 'Requires attribution',
    'not-accepted': 'Not accepted',
  },
  ai_cicd: {
    'permitted': 'Permitted',
    'restricted': 'Restricted',
    'prohibited': 'Prohibited',
  },
  training_optout: {
    'yes': 'Yes',
    'no': 'No',
  },
  test_reqs: {
    'none': 'None',
    'recommended': 'Recommended',
    'required-before-merge': 'Required before merge',
  },
  review_reqs: {
    'none': 'None',
    'significant-changes': 'Significant changes',
    'all-ai-prs': 'All AI-generated PRs',
  },
};

const FOOTER = '\n---\n*Generated by [aipolicy.1mb.dev](https://aipolicy.1mb.dev) · v1.0*\n';

// ============================================
// Template Functions
// ============================================

function escapeMarkdown(str) {
  if (!str) return '';
  return str.replace(/[<>&"']/g, (c) => {
    const map = { '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&#39;' };
    return map[c];
  });
}

function generateAiPolicy(opts) {
  const usage = LABELS.ai_usage[opts.ai_usage] || opts.ai_usage;
  const code = LABELS.ai_code[opts.ai_code] || opts.ai_code;
  const cicd = LABELS.ai_cicd[opts.ai_cicd] || opts.ai_cicd;
  const optout = opts.training_optout === 'yes';

  let md = `# AI Policy

This document declares how AI tools are used in this project.

## AI Tool Usage

**Policy:** ${usage}

`;

  if (opts.ai_usage === 'permitted') {
    md += `AI-powered development tools may be used without restriction. Contributors are free to use AI assistants for code generation, review, and documentation.\n\n`;
  } else if (opts.ai_usage === 'permitted-with-review') {
    md += `AI-powered development tools may be used, but AI-assisted contributions must go through the standard review process. Reviewers should be aware when a contribution involved AI assistance.\n\n`;
  } else if (opts.ai_usage === 'restricted') {
    md += `AI tool usage is restricted. Contributors must obtain approval before using AI tools for contributions to this project. Approved use cases and tools will be documented below.\n\n`;
  } else {
    md += `AI-powered development tools are not permitted for contributions to this project. All contributions must be human-authored.\n\n`;
  }

  md += `## AI-Generated Code

**Policy:** ${code}

`;

  if (opts.ai_code === 'accepted') {
    md += `AI-generated code is accepted in this project. No special attribution or review process is required beyond the standard contribution workflow.\n\n`;
  } else if (opts.ai_code === 'requires-review') {
    md += `AI-generated code is accepted but must be reviewed by a human maintainer before merging. Contributors should indicate when a pull request contains AI-generated code.\n\n`;
  } else if (opts.ai_code === 'requires-attribution') {
    md += `AI-generated code is accepted but must be clearly attributed. Pull requests containing AI-generated code should note which portions were AI-generated and which tool was used.\n\n`;
  } else {
    md += `AI-generated code is not accepted in this project. All code contributions must be human-authored. Pull requests identified as containing AI-generated code will not be merged.\n\n`;
  }

  md += `## AI in CI/CD

**Policy:** ${cicd}

`;

  if (opts.ai_cicd === 'permitted') {
    md += `AI tools may be used in CI/CD pipelines, including automated code analysis, test generation, and deployment assistance.\n\n`;
  } else if (opts.ai_cicd === 'restricted') {
    md += `AI tools in CI/CD pipelines require explicit approval. Any AI-powered automation must be reviewed and approved by a maintainer before integration into the pipeline.\n\n`;
  } else {
    md += `AI tools are not permitted in CI/CD pipelines. All automated processes must use deterministic, non-AI tooling.\n\n`;
  }

  md += `## Training Data

**Opt-out:** ${optout ? 'Yes' : 'No'}

`;

  if (optout) {
    md += `This project requests that its code not be used for AI model training. This preference should be respected by AI tool providers and data collection services.\n`;
  } else {
    md += `This project does not opt out of AI training data collection. Standard platform terms apply.\n`;
  }

  md += FOOTER;
  return md;
}

function generateAgents(opts) {
  const testLabel = LABELS.test_reqs[opts.test_reqs] || opts.test_reqs;
  const reviewLabel = LABELS.review_reqs[opts.review_reqs] || opts.review_reqs;
  const codeStyle = escapeMarkdown(opts.code_style);
  const restrictedPaths = escapeMarkdown(opts.restricted_paths);

  let md = `# Agents

Rules and guidelines for AI coding agents working in this repository.

## General

- Follow existing code conventions and patterns
- Do not modify files outside the scope of the assigned task
- Ask for clarification rather than making assumptions about ambiguous requirements
`;

  if (codeStyle) {
    md += `\n## Code Style\n\n${codeStyle}\n`;
  }

  md += `\n## Testing\n\n**Requirement:** ${testLabel}\n\n`;

  if (opts.test_reqs === 'none') {
    md += `No specific testing requirements for AI-generated changes. Follow the project's existing testing conventions if any.\n`;
  } else if (opts.test_reqs === 'recommended') {
    md += `Tests are recommended for AI-generated changes. Include tests for new functionality and verify that existing tests pass before submitting.\n`;
  } else {
    md += `Tests are required for all AI-generated changes. Pull requests without adequate test coverage will not be merged. Run the full test suite before submitting.\n`;
  }

  if (restrictedPaths) {
    const paths = restrictedPaths.split(',').map(p => p.trim()).filter(Boolean);
    md += `\n## Restricted Paths\n\nDo not modify the following files or directories:\n\n`;
    for (const p of paths) {
      md += `- \`${p}\`\n`;
    }
  }

  md += `\n## Review\n\n**Requirement:** ${reviewLabel}\n\n`;

  if (opts.review_reqs === 'none') {
    md += `No special review requirements for AI-generated pull requests beyond the standard process.\n`;
  } else if (opts.review_reqs === 'significant-changes') {
    md += `Pull requests with significant AI-generated changes require human review. Minor fixes and documentation updates may follow the standard process.\n`;
  } else {
    md += `All AI-generated pull requests require human review before merging, regardless of scope or size.\n`;
  }

  md += FOOTER;
  return md;
}

function generateClaude(opts) {
  if (opts.claude_handling === 'symlink') {
    return `# CLAUDE.md

This file can be replaced with a symlink to AGENTS.md:

\`\`\`
ln -sf AGENTS.md CLAUDE.md
\`\`\`

The rules in AGENTS.md apply to Claude Code. No additional Claude-specific configuration is needed.
${FOOTER}`;
  }

  let md = `# CLAUDE.md

Configuration for Claude Code in this repository. See AGENTS.md for general agent rules.

## Applies

All rules from AGENTS.md apply to Claude Code sessions in this repository.

`;

  if (opts.test_reqs === 'required-before-merge') {
    md += `## Testing

Run the full test suite before proposing changes. Do not submit pull requests with failing tests.

`;
  }

  if (opts.restricted_paths) {
    md += `## Restricted

Do not read or modify files listed in the Restricted Paths section of AGENTS.md.

`;
  }

  md += `## Behavior

- Prefer editing existing files over creating new ones
- Keep changes minimal and focused on the task
- Do not add dependencies without explicit approval
`;

  md += FOOTER;
  return md;
}

// ============================================
// State
// ============================================

const state = {
  preset: 'standard',
  options: { ...PRESETS.standard },
  activeTab: 'policy',
  modified: false,
};

function getGeneratedFiles() {
  return {
    policy: generateAiPolicy(state.options),
    agents: generateAgents(state.options),
    claude: generateClaude(state.options),
  };
}

// ============================================
// Render
// ============================================

function renderPreview() {
  const files = getGeneratedFiles();
  const panels = {
    policy: document.getElementById('panel-policy'),
    agents: document.getElementById('panel-agents'),
    claude: document.getElementById('panel-claude'),
  };

  for (const [key, el] of Object.entries(panels)) {
    if (el) el.textContent = files[key];
  }
}

function initPreview() {
  renderPreview();
}

// ============================================
// Theme Toggle
// ============================================

function initTheme() {
  const toggle = document.querySelector('.theme-toggle');
  if (!toggle) return;

  let stored = 'auto';
  try {
    const val = localStorage.getItem('aipolicy-theme');
    if (val === 'light' || val === 'dark' || val === 'auto') stored = val;
  } catch (e) {
    // localStorage unavailable (private browsing) -- default to auto
  }

  applyTheme(stored);
  updateToggleState(toggle, stored);

  toggle.addEventListener('click', (e) => {
    const btn = e.target.closest('button[data-theme-value]');
    if (!btn) return;
    const value = btn.dataset.themeValue;
    applyTheme(value);
    updateToggleState(toggle, value);
    try {
      if (value === 'auto') {
        localStorage.removeItem('aipolicy-theme');
      } else {
        localStorage.setItem('aipolicy-theme', value);
      }
    } catch (e) {
      // localStorage unavailable -- theme still applied for this session
    }
  });
}

function applyTheme(value) {
  if (value === 'auto') {
    document.documentElement.removeAttribute('data-theme');
  } else {
    document.documentElement.setAttribute('data-theme', value);
  }
}

function updateToggleState(toggle, active) {
  for (const btn of toggle.querySelectorAll('button')) {
    btn.setAttribute('aria-pressed', btn.dataset.themeValue === active ? 'true' : 'false');
  }
}

// ============================================
// Init
// ============================================

document.addEventListener('DOMContentLoaded', () => {
  initTheme();
  initPreview();
});
