#!/usr/bin/env node
// Test that all preset template outputs are valid markdown.
// Generates every preset, writes to a temp dir, runs markdownlint.
// Run: node scripts/test-presets.js

import { writeFileSync, mkdirSync, rmSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execFileSync } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const tmpDir = join(root, '.tmp-test-presets');

// Preset definitions (same as generate-presets.js)
const PRESETS = {
  permissive: { ai_usage: 'permitted', ai_code: 'accepted', ai_cicd: 'permitted', training_optout: 'no', code_style: '', test_reqs: 'none', restricted_paths: '', review_reqs: 'none', claude_handling: 'separate' },
  standard: { ai_usage: 'permitted-with-review', ai_code: 'requires-review', ai_cicd: 'permitted', training_optout: 'yes', code_style: '', test_reqs: 'recommended', restricted_paths: '', review_reqs: 'significant-changes', claude_handling: 'separate' },
  strict: { ai_usage: 'restricted', ai_code: 'not-accepted', ai_cicd: 'restricted', training_optout: 'yes', code_style: '', test_reqs: 'required-before-merge', restricted_paths: '', review_reqs: 'all-ai-prs', claude_handling: 'separate' },
};

// Additional test combinations that exercise freeform input + edge cases
const EXTRA_COMBOS = {
  'standard-with-freeform': {
    ...PRESETS.standard,
    code_style: 'Follow airbnb/javascript. Use 2-space indentation.',
    restricted_paths: '.env, secrets/, config/production.yml',
  },
  'strict-with-attribution': {
    ...PRESETS.strict,
    ai_code: 'requires-attribution',
  },
  'permissive-symlink': {
    ...PRESETS.permissive,
    claude_handling: 'symlink',
  },
  'strict-prohibited': {
    ...PRESETS.strict,
    ai_usage: 'prohibited',
    ai_cicd: 'prohibited',
  },
};

const ALL = { ...PRESETS, ...EXTRA_COMBOS };

// Import template functions from generate-presets.js
// We use dynamic import since it's an ES module
const genModule = join(root, 'scripts', 'generate-presets.js');

// Since generate-presets.js writes files as a side effect, we duplicate
// the template functions here. This is intentional -- the test validates
// template OUTPUT, not the generate script itself.

const LABELS = {
  ai_usage: { 'permitted': 'Permitted', 'permitted-with-review': 'Permitted with review', 'restricted': 'Restricted', 'prohibited': 'Prohibited' },
  ai_code: { 'accepted': 'Accepted', 'requires-review': 'Requires review', 'requires-attribution': 'Requires attribution', 'not-accepted': 'Not accepted' },
  ai_cicd: { 'permitted': 'Permitted', 'restricted': 'Restricted', 'prohibited': 'Prohibited' },
  test_reqs: { 'none': 'None', 'recommended': 'Recommended', 'required-before-merge': 'Required before merge' },
  review_reqs: { 'none': 'None', 'significant-changes': 'Significant changes', 'all-ai-prs': 'All AI-generated PRs' },
};

const FOOTER = '\n---\n*Generated by [aipolicy.1mb.dev](https://aipolicy.1mb.dev) · v1.0*\n';

function escapeMarkdown(str) {
  if (!str) return '';
  return str.replace(/[<>&"']/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&#39;' })[c]);
}

function generateAiPolicy(opts) {
  const usage = LABELS.ai_usage[opts.ai_usage] || opts.ai_usage;
  const code = LABELS.ai_code[opts.ai_code] || opts.ai_code;
  const cicd = LABELS.ai_cicd[opts.ai_cicd] || opts.ai_cicd;
  const optout = opts.training_optout === 'yes';
  let md = `# AI Policy\n\nThis document declares how AI tools are used in this project and what is expected of contributors who use them.\n\n## Accountability\n\nYou are responsible for every line of code you submit, regardless of how it was produced. If you use AI tools, you must review, understand, and verify all output before committing it.\n\n## AI Tool Usage\n\n**Policy:** ${usage}\n\n`;
  if (opts.ai_usage === 'permitted') md += `AI-powered development tools may be used without restriction for code generation, review, and documentation.\n\n`;
  else if (opts.ai_usage === 'permitted-with-review') md += `AI-powered development tools may be used, but AI-assisted contributions must go through the standard review process. Reviewers should be aware when a contribution involved AI assistance.\n\n`;
  else if (opts.ai_usage === 'restricted') md += `AI tool usage is restricted. Obtain approval before using AI tools for contributions to this project.\n\n`;
  else md += `AI-powered development tools are not permitted for contributions to this project. All contributions must be human-authored.\n\n`;
  md += `## AI-Generated Code\n\n**Policy:** ${code}\n\n`;
  if (opts.ai_code === 'accepted') md += `AI-generated code is accepted. No special attribution or review process is required beyond the standard contribution workflow.\n\n`;
  else if (opts.ai_code === 'requires-review') md += `AI-generated code must be reviewed by a human maintainer before merging. Contributors should indicate when a pull request contains AI-generated code.\n\n`;
  else if (opts.ai_code === 'requires-attribution') md += `AI-generated code must be clearly attributed. Use a commit trailer to indicate AI involvement:\n\n\`\`\`\nAssisted-by: <tool name>\n\`\`\`\n\nPull requests should note which portions were AI-generated and which tool was used.\n\n`;
  else md += `AI-generated code is not accepted. Pull requests identified as containing AI-generated code will not be merged.\n\n`;
  md += `## AI in CI/CD\n\n**Policy:** ${cicd}\n\n`;
  if (opts.ai_cicd === 'permitted') md += `AI tools may be used in CI/CD pipelines, including automated code analysis, test generation, and deployment assistance.\n\n`;
  else if (opts.ai_cicd === 'restricted') md += `AI tools in CI/CD pipelines require explicit maintainer approval before integration.\n\n`;
  else md += `AI tools are not permitted in CI/CD pipelines. All automated processes must use deterministic, non-AI tooling.\n\n`;
  md += `## Training Data\n\n**Opt-out:** ${optout ? 'Yes' : 'No'}\n\n`;
  if (optout) md += `This project requests that its code not be used for AI model training. This preference should be respected by AI tool providers and data collection services.\n\n`;
  else md += `This project does not opt out of AI training data collection. Standard platform terms apply.\n\n`;
  md += `## Policy Evolution\n\nThis policy will be updated as AI tooling and legal standards change. Propose updates via pull request.\n`;
  md += FOOTER;
  return md;
}

function generateAgents(opts) {
  const testLabel = LABELS.test_reqs[opts.test_reqs] || opts.test_reqs;
  const reviewLabel = LABELS.review_reqs[opts.review_reqs] || opts.review_reqs;
  const codeStyle = escapeMarkdown(opts.code_style);
  const restrictedPaths = escapeMarkdown(opts.restricted_paths);
  let md = `# Agents\n\nInstructions for AI coding agents working in this repository.\n\n## Rules\n\n- Follow existing code conventions and patterns in the codebase\n- Do not modify files outside the scope of the current task\n- Prefer editing existing files over creating new ones\n- Do not add dependencies without explicit approval\n- Ask for clarification when requirements are ambiguous\n`;
  if (codeStyle) md += `\n## Code Style\n\n${codeStyle}\n`;
  md += `\n## Setup\n\n<!-- Replace with your project's actual commands -->\n<!-- npm install / go build / make / etc. -->\n\n## Testing\n\n**Requirement:** ${testLabel}\n\n`;
  if (opts.test_reqs === 'none') md += `Follow the project's existing testing conventions.\n`;
  else if (opts.test_reqs === 'recommended') md += `Include tests for new functionality. Verify existing tests pass before submitting.\n`;
  else md += `Tests are required for all changes. Run the full test suite before submitting. Pull requests without adequate test coverage will not be merged.\n`;
  if (restrictedPaths) {
    const paths = restrictedPaths.split(',').map(p => p.trim()).filter(Boolean);
    md += `\n## Restricted Paths\n\nDo not read or modify:\n\n`;
    for (const p of paths) md += `- \`${p}\`\n`;
  }
  md += `\n## Review\n\n**Requirement:** ${reviewLabel}\n\n`;
  if (opts.review_reqs === 'none') md += `No special review requirements beyond the standard process.\n`;
  else if (opts.review_reqs === 'significant-changes') md += `Significant AI-generated changes require human review. Minor fixes and documentation updates may follow the standard process.\n`;
  else md += `All AI-generated pull requests require human review before merging, regardless of scope.\n`;
  md += FOOTER;
  return md;
}

function generateClaude(opts) {
  if (opts.claude_handling === 'symlink') {
    return `# CLAUDE.md\n\nThis file can be replaced with a symlink to AGENTS.md:\n\n\`\`\`\nln -sf AGENTS.md CLAUDE.md\n\`\`\`\n\nAll rules in AGENTS.md apply to Claude Code sessions.\n${FOOTER}`;
  }
  let md = `# CLAUDE.md\n\nClaude Code configuration. All rules from AGENTS.md apply.\n\n`;
  if (opts.test_reqs === 'required-before-merge') md += `## Testing\n\nRun the full test suite before proposing changes. Do not submit with failing tests.\n\n`;
  if (opts.restricted_paths) md += `## Restricted\n\nDo not read or modify files listed under Restricted Paths in AGENTS.md.\n\n`;
  md += `## Behavior\n\n- Keep changes minimal and focused\n- Verify your changes work before submitting\n- When uncertain, ask rather than assume\n`;
  md += FOOTER;
  return md;
}

// Generate all combinations to temp dir
if (existsSync(tmpDir)) rmSync(tmpDir, { recursive: true });

let fileCount = 0;
for (const [name, opts] of Object.entries(ALL)) {
  const dir = join(tmpDir, name);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'AI_POLICY.md'), generateAiPolicy(opts));
  writeFileSync(join(dir, 'AGENTS.md'), generateAgents(opts));
  writeFileSync(join(dir, 'CLAUDE.md'), generateClaude(opts));
  fileCount += 3;
}

console.log(`Generated ${fileCount} files across ${Object.keys(ALL).length} combinations.`);

// Run markdownlint on all generated files
const mdlintBin = join(root, 'node_modules', '.bin', 'markdownlint-cli2');
try {
  execFileSync(mdlintBin, [`${tmpDir}/**/*.md`], { stdio: 'inherit' });
  console.log('All generated markdown passes lint.');
} catch (e) {
  console.error('Markdown lint failures in generated output. Fix templates.');
  rmSync(tmpDir, { recursive: true });
  process.exit(1);
}

// Cleanup
rmSync(tmpDir, { recursive: true });
console.log(`Tested ${Object.keys(ALL).length} preset combinations -- all clean.`);
